### ISSUE TITLE
Padding in iOS

### ISSUE THREAD

**Issue by renatotozzi** [stormlion227/SNavigation.Forms#1]
Hi guy

Why in iOS the NavigationBar takes a padding bottom, below the SearchBox, leaving large NavigationBar heigth? Is there a way to take this padding away?

**Comment by stormlion227** [comment]
Would you explain carefully?
I can't understand what does mean.

**Comment by renatotozzi** [comment]
Hi, sorry my bad English, so I will show screenshot.

Notice that in screenshot from SNavgation, the navigation bar is larger than the other screenshot (which I I've made manually whithout navigation bar).

In android it does not happen, the navigation bar stays in you default size.

With SNavigation | Without SNavigation
------------------- | -----------------------
![20180412_030219040_ios-snavigation](https://user-images.githubusercontent.com/6411176/38944691-8ea6f302-4302-11e8-9fb9-89c055c40c9d.png) | ![20180412_030219040_ios-swithoutnavigation](https://user-images.githubusercontent.com/6411176/38944703-936fab18-4302-11e8-9bb5-53142d8b586a.png)

**Comment by stormlion227** [comment]
Thanks for reporting issue.
I'll fix by tomorrow.

Thanks again.

**Comment by renatotozzi** [comment]
U welcome!

I'll wait the package update =)

**Comment by stormlion227** [comment]
I've checked. I can't reproduce this issue.

Would you share your XAML code?

**Comment by renatotozzi** [comment]
My XAML has nothing special, it folows like this:

<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:snav="clr-namespace:Stormlion.SNavigation;assembly=Stormlion.SNavigation"
             x:Class="TesteApp.MainPage">

    <snav:SNavigationPage.NavContent>
        <Grid Margin="50, 0, 50, 0">
            <SearchBar BackgroundColor="Transparent" Placeholder="Search ..."/>
        </Grid>
    </snav:SNavigationPage.NavContent>
    <ContentPage.Content>
    </ContentPage.Content>

</ContentPage>

The problem is only padding top and bottom in the SearchBar, it's too large, and it happens only in iPhone.

**Comment by mrxten** [comment]
@renatotozzi I think problem not in this lib, since in ios its just subview under toolbar.
SearchBar just has too big height for ios toolbar. Try make searchbar less or toolbar more bigger.

**Comment by mrxten** [comment]
or try
`<SearchBar VerticalOptions="CenterAndExpand" BackgroundColor="Transparent" Placeholder="Search ..."/>`

**Comment by renatotozzi** [comment]
Ok @mrxten I'll try to do that. It's strange because I have a clean project and I think there is no another thing causing this behavior. And also in Android it works perfectly.

**Comment by mrxten** [comment]
@renatotozzi  in android more bigger toolbar height.

**Comment by renatotozzi** [comment]
Hi all

I removed all SNavigation references in my project and added again, and now it works fine! =)

Thanks for help me
